// Mock data for AI Game Analysis feature development

import {
  GameAnalysis,
  AnalyzedGameSummary,
  GameError,
  CoachingTip,
  VideoClip,
  AnalysisStats,
  ErrorType,
  ErrorSeverity,
} from '@/types/analysis';

// Mock errors for a game
const mockErrors: GameError[] = [
  {
    id: 'err-1',
    type: 'positioning',
    severity: 'critical',
    title: 'Caught out of position in teamfight',
    description: 'You were positioned too far forward without vision of the enemy jungler. This allowed the enemy team to collapse on you, resulting in your death and losing the teamfight.',
    timestamp: 847,
    suggestion: 'Stay behind your frontline and wait for key enemy abilities to be used before moving forward. Always check minimap for missing enemies.',
    videoClip: {
      start: 842,
      end: 858,
      url: '/mock-clips/positioning-error-1.mp4',
    },
  },
  {
    id: 'err-2',
    type: 'cs-missing',
    severity: 'medium',
    title: 'Missed cannon minion under tower',
    description: 'You missed a cannon minion worth 60+ gold while farming under tower. The tower took 2 shots before you auto-attacked.',
    timestamp: 312,
    suggestion: 'For cannon minions under tower: let tower hit twice, then auto-attack. Practice last-hitting under tower in practice tool.',
    videoClip: {
      start: 308,
      end: 318,
      url: '/mock-clips/cs-error-1.mp4',
    },
  },
  {
    id: 'err-3',
    type: 'vision',
    severity: 'high',
    title: 'No vision before Drake',
    description: 'Your team started Dragon without clearing enemy vision or establishing control wards. The enemy team was able to contest because they saw your team on the objective.',
    timestamp: 1205,
    suggestion: 'Before starting any objective, sweep the area with Oracle Lens and place a control ward. This denies enemy vision and allows for safer objective takes.',
    videoClip: {
      start: 1195,
      end: 1230,
      url: '/mock-clips/vision-error-1.mp4',
    },
  },
  {
    id: 'err-4',
    type: 'trading',
    severity: 'medium',
    title: 'Bad trade in lane',
    description: 'You traded into the enemy when they had minion advantage. You took 150 extra damage from minions, losing the trade significantly.',
    timestamp: 185,
    suggestion: 'Always check minion count before trading. Having 4+ more enemy minions means you should avoid extended trades.',
    videoClip: {
      start: 180,
      end: 195,
      url: '/mock-clips/trading-error-1.mp4',
    },
  },
  {
    id: 'err-5',
    type: 'map-awareness',
    severity: 'critical',
    title: 'Ganked due to no map awareness',
    description: 'Enemy jungler was visible on a ward 10 seconds before the gank, but you continued pushing without backing off. This resulted in a death.',
    timestamp: 456,
    suggestion: 'Glance at your minimap every 3-5 seconds. When you see the enemy jungler, immediately adjust your position.',
    videoClip: {
      start: 446,
      end: 468,
      url: '/mock-clips/map-awareness-error-1.mp4',
    },
  },
  {
    id: 'err-6',
    type: 'objective',
    severity: 'high',
    title: 'Poor Baron call',
    description: 'Your team started Baron when 3 enemies were alive and their jungler had Smite available. This is a high-risk call that resulted in a Baron steal.',
    timestamp: 1845,
    suggestion: 'Ideal Baron timing: enemy jungler dead, or at least 3 enemies dead. Always track enemy jungler before starting Baron.',
    videoClip: {
      start: 1835,
      end: 1870,
      url: '/mock-clips/objective-error-1.mp4',
    },
  },
  {
    id: 'err-7',
    type: 'wave-management',
    severity: 'low',
    title: 'Slow push not executed properly',
    description: 'You broke your slow push by killing all minions too fast. This denied you a large wave crash before your recall.',
    timestamp: 623,
    suggestion: 'For slow pushes, only last-hit minions. Let your minions naturally build up for 2-3 waves before hard pushing.',
  },
  {
    id: 'err-8',
    type: 'cooldown-tracking',
    severity: 'medium',
    title: 'Engaged without tracking Flash',
    description: 'You engaged on the enemy ADC who had Flash available. They Flashed your combo and you ended up in a bad position.',
    timestamp: 1102,
    suggestion: 'Track enemy summoner spells. Flash cooldown is 5 minutes. Ping when enemies use summoners to help your team track.',
  },
];

// Mock coaching tips
const mockTips: CoachingTip[] = [
  {
    id: 'tip-1',
    category: 'Map Awareness',
    title: 'Develop a minimap checking habit',
    description: 'You died twice to ganks that were visible on the minimap. Set a mental reminder to check the minimap every 3 CS or every ability cast. This habit will significantly reduce your deaths from ganks.',
    priority: 1,
    relatedErrors: ['err-5'],
    icon: 'map',
  },
  {
    id: 'tip-2',
    category: 'Positioning',
    title: 'Respect enemy engage ranges',
    description: 'In teamfights, you consistently stood within enemy engage range. Know the range of key enemy abilities and position just outside them. Let your frontline absorb cooldowns first.',
    priority: 2,
    relatedErrors: ['err-1'],
    icon: 'target',
  },
  {
    id: 'tip-3',
    category: 'CS Fundamentals',
    title: 'Practice tower CS patterns',
    description: 'You missed 3 minions under tower. The pattern is: Melee = 2 tower shots + 1 auto. Caster = 1 auto + tower shot + 1 auto. Cannon = many tower shots + last hit. Spend 10 mins in practice tool daily.',
    priority: 3,
    relatedErrors: ['err-2'],
    icon: 'coins',
  },
  {
    id: 'tip-4',
    category: 'Vision Control',
    title: 'Establish vision before objectives',
    description: 'Your team lost Dragon and Baron due to enemy vision. Always sweep and place a control ward 30-60 seconds before objectives spawn. Vision wins games.',
    priority: 4,
    relatedErrors: ['err-3', 'err-6'],
    icon: 'eye',
  },
  {
    id: 'tip-5',
    category: 'Trading',
    title: 'Respect minion damage early',
    description: 'Early game minions deal significant damage. A full wave can deal 200+ damage. Only take extended trades when you have minion advantage or the wave is neutral.',
    priority: 5,
    relatedErrors: ['err-4'],
    icon: 'swords',
  },
];

// Mock video clips
const mockClips: VideoClip[] = [
  {
    id: 'clip-1',
    type: 'error',
    timestamp: 847,
    duration: 16,
    title: 'Teamfight positioning error',
    description: 'Critical positioning mistake leading to death',
    url: '/mock-clips/teamfight-death.mp4',
    thumbnailUrl: '/mock-thumbnails/teamfight-death.jpg',
  },
  {
    id: 'clip-2',
    type: 'death',
    timestamp: 456,
    duration: 22,
    title: 'Gank death - No map awareness',
    description: 'Died to gank despite ward vision',
    url: '/mock-clips/gank-death.mp4',
    thumbnailUrl: '/mock-thumbnails/gank-death.jpg',
  },
  {
    id: 'clip-3',
    type: 'error',
    timestamp: 1845,
    duration: 35,
    title: 'Baron stolen',
    description: 'Poor Baron call resulting in steal',
    url: '/mock-clips/baron-steal.mp4',
    thumbnailUrl: '/mock-thumbnails/baron-steal.jpg',
  },
  {
    id: 'clip-4',
    type: 'highlight',
    timestamp: 1520,
    duration: 18,
    title: 'Triple kill in teamfight',
    description: 'Good positioning leading to multi-kill',
    url: '/mock-clips/triple-kill.mp4',
    thumbnailUrl: '/mock-thumbnails/triple-kill.jpg',
  },
];

// Mock analysis stats
const mockStats: AnalysisStats = {
  overallScore: 68,
  csScore: 72,
  visionScore: 58,
  positioningScore: 61,
  objectiveScore: 65,
  tradingScore: 70,
  deathsAnalyzed: 5,
  errorsFound: 8,
  comparedToRank: [
    { metric: 'CS per minute', yours: 7.2, average: 6.8, percentile: 62 },
    { metric: 'Vision score', yours: 18, average: 24, percentile: 35 },
    { metric: 'Deaths per game', yours: 5, average: 4.2, percentile: 42 },
    { metric: 'Kill participation', yours: 68, average: 58, percentile: 71 },
    { metric: 'Damage per minute', yours: 820, average: 750, percentile: 65 },
    { metric: 'Gold per minute', yours: 410, average: 380, percentile: 68 },
  ],
};

// Full mock game analysis
export const mockGameAnalysis: GameAnalysis = {
  id: 'analysis-1',
  matchId: 'EUW1_7123456789',
  puuid: 'mock-puuid-12345',
  status: 'completed',
  createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  completedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  champion: 'Jinx',
  result: 'loss',
  duration: 2134,
  gameMode: 'Ranked Solo/Duo',
  kills: 8,
  deaths: 5,
  assists: 12,
  stats: mockStats,
  errors: mockErrors,
  tips: mockTips,
  clips: mockClips,
};

// List of analyzed games summaries
export const mockAnalyzedGames: AnalyzedGameSummary[] = [
  {
    id: 'analysis-1',
    matchId: 'EUW1_7123456789',
    champion: 'Jinx',
    result: 'loss',
    duration: 2134,
    overallScore: 68,
    errorsCount: 8,
    status: 'completed',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    kills: 8,
    deaths: 5,
    assists: 12,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-2',
    matchId: 'EUW1_7123456790',
    champion: 'Caitlyn',
    result: 'win',
    duration: 1856,
    overallScore: 82,
    errorsCount: 4,
    status: 'completed',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    kills: 12,
    deaths: 2,
    assists: 8,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-3',
    matchId: 'EUW1_7123456791',
    champion: 'Ezreal',
    result: 'loss',
    duration: 2456,
    overallScore: 54,
    errorsCount: 12,
    status: 'completed',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    kills: 5,
    deaths: 8,
    assists: 6,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-4',
    matchId: 'EUW1_7123456792',
    champion: 'Vayne',
    result: 'win',
    duration: 1678,
    overallScore: 91,
    errorsCount: 2,
    status: 'completed',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    kills: 15,
    deaths: 1,
    assists: 10,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-5',
    matchId: 'EUW1_7123456793',
    champion: 'Kai\'Sa',
    result: 'win',
    duration: 2012,
    overallScore: 75,
    errorsCount: 5,
    status: 'completed',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    kills: 10,
    deaths: 3,
    assists: 14,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-6',
    matchId: 'EUW1_7123456794',
    champion: 'Ashe',
    result: 'loss',
    duration: 1923,
    overallScore: 45,
    errorsCount: 15,
    status: 'completed',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    kills: 3,
    deaths: 9,
    assists: 7,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
  {
    id: 'analysis-7',
    matchId: 'EUW1_7123456795',
    champion: 'Jinx',
    result: 'win',
    duration: 2234,
    overallScore: 0,
    errorsCount: 0,
    status: 'processing',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    kills: 9,
    deaths: 4,
    assists: 11,
    role: 'ADC',
    gameMode: 'CLASSIC',
  },
];

// Generate a second detailed analysis for testing
export const mockGameAnalysis2: GameAnalysis = {
  id: 'analysis-2',
  matchId: 'EUW1_7123456790',
  puuid: 'mock-puuid-12345',
  status: 'completed',
  createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  completedAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
  champion: 'Caitlyn',
  result: 'win',
  duration: 1856,
  gameMode: 'Ranked Solo/Duo',
  kills: 12,
  deaths: 2,
  assists: 8,
  stats: {
    overallScore: 82,
    csScore: 88,
    visionScore: 75,
    positioningScore: 85,
    objectiveScore: 78,
    tradingScore: 82,
    deathsAnalyzed: 2,
    errorsFound: 4,
    comparedToRank: [
      { metric: 'CS per minute', yours: 8.5, average: 6.8, percentile: 85 },
      { metric: 'Vision score', yours: 28, average: 24, percentile: 68 },
      { metric: 'Deaths per game', yours: 2, average: 4.2, percentile: 82 },
      { metric: 'Kill participation', yours: 72, average: 58, percentile: 78 },
      { metric: 'Damage per minute', yours: 950, average: 750, percentile: 82 },
      { metric: 'Gold per minute', yours: 480, average: 380, percentile: 85 },
    ],
  },
  errors: [
    {
      id: 'err-a1',
      type: 'positioning',
      severity: 'medium',
      title: 'Stepped too far forward',
      description: 'You moved forward to poke but got hit by enemy CC.',
      timestamp: 623,
      suggestion: 'Keep maximum auto-attack range from enemy engage threats.',
    },
    {
      id: 'err-a2',
      type: 'vision',
      severity: 'low',
      title: 'Late ward placement',
      description: 'You placed your ward after the enemy jungler had already pathed past the area.',
      timestamp: 412,
      suggestion: 'Place wards proactively based on expected enemy jungle pathing.',
    },
    {
      id: 'err-a3',
      type: 'cs-missing',
      severity: 'low',
      title: 'Missed 2 minions during trade',
      description: 'While trading with the enemy, you missed 2 caster minions.',
      timestamp: 345,
      suggestion: 'Try to weave auto-attacks on minions between trading patterns.',
    },
    {
      id: 'err-a4',
      type: 'objective',
      severity: 'medium',
      title: 'Could have secured dragon faster',
      description: 'Your team killed dragon slowly without using abilities efficiently.',
      timestamp: 1234,
      suggestion: 'Save trap charges for dragon to maximize DPS on objectives.',
    },
  ],
  tips: [
    {
      id: 'tip-a1',
      category: 'Excellent Performance',
      title: 'Great CS numbers!',
      description: 'Your CS this game was exceptional. You\'re in the top 15% for your rank. Keep maintaining this level of farm focus.',
      priority: 1,
      icon: 'coins',
    },
    {
      id: 'tip-a2',
      category: 'Trading',
      title: 'Efficient trading patterns',
      description: 'You used Caitlyn\'s range advantage well in lane. Your headshot management was particularly good.',
      priority: 2,
      icon: 'swords',
    },
  ],
  clips: [
    {
      id: 'clip-a1',
      type: 'highlight',
      timestamp: 1456,
      duration: 20,
      title: 'Perfect teamfight positioning',
      description: 'Excellent positioning leading to quadra kill',
      url: '/mock-clips/quadra-kill.mp4',
      thumbnailUrl: '/mock-thumbnails/quadra-kill.jpg',
    },
  ],
};

// Helper function to get analysis by ID
export function getMockAnalysisById(id: string): GameAnalysis | undefined {
  if (id === 'analysis-1') return mockGameAnalysis;
  if (id === 'analysis-2') return mockGameAnalysis2;
  return undefined;
}

// Helper to get overall statistics across all games
export function getMockOverallStats() {
  const completedGames = mockAnalyzedGames.filter(g => g.status === 'completed');
  const totalGames = completedGames.length;
  const avgScore = completedGames.reduce((sum, g) => sum + g.overallScore, 0) / totalGames;
  const totalErrors = completedGames.reduce((sum, g) => sum + g.errorsCount, 0);
  const wins = completedGames.filter(g => g.result === 'win').length;

  return {
    totalGames,
    avgScore: Math.round(avgScore),
    totalErrors,
    avgErrorsPerGame: Math.round(totalErrors / totalGames * 10) / 10,
    winRate: Math.round((wins / totalGames) * 100),
    mostCommonErrors: [
      { type: 'positioning' as ErrorType, count: 12 },
      { type: 'vision' as ErrorType, count: 9 },
      { type: 'cs-missing' as ErrorType, count: 8 },
      { type: 'map-awareness' as ErrorType, count: 6 },
      { type: 'objective' as ErrorType, count: 5 },
    ],
  };
}
