/**
 * EXEMPLES ET TESTS DE L'ALGORITHME
 * Cas d'usage concrets pour tester la probabilité de victoire
 */

import {
  calculateMatchWinProbability,
  PlayerData,
  TeamData,
  WEIGHTS,
} from './winProbabilityCalculator';

// ==========================================
// CAS 1: Match équilibré (50/50)
// ==========================================

export const BALANCED_MATCH = {
  yourTeam: {
    players: [
      {
        summonerName: 'TopPlayer',
        role: 'TOP' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 50,
        championName: 'Darius',
        championMastery: 5,
        gamesOnChampion: 25,
        winrateOnChampion: 52,
        kdaOnChampion: 2.3,
        globalWinrate: 50,
        totalGames: 200,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'JunglePlayer',
        role: 'JUNGLE' as const,
        tier: 'GOLD' as const,
        division: 'III' as const,
        leaguePoints: 30,
        championName: 'LeeSin',
        championMastery: 6,
        gamesOnChampion: 40,
        winrateOnChampion: 51,
        kdaOnChampion: 2.5,
        globalWinrate: 49,
        totalGames: 180,
        isMainRole: true,
        isAutofill: false,
        recentWins: 4,
        recentGames: 10,
        currentStreak: -1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'MidPlayer',
        role: 'MID' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 60,
        championName: 'Ahri',
        championMastery: 5,
        gamesOnChampion: 30,
        winrateOnChampion: 53,
        kdaOnChampion: 2.8,
        globalWinrate: 51,
        totalGames: 220,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'ADCPlayer',
        role: 'ADC' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 45,
        championName: 'Jinx',
        championMastery: 4,
        gamesOnChampion: 20,
        winrateOnChampion: 50,
        kdaOnChampion: 2.6,
        globalWinrate: 50,
        totalGames: 190,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'SupportPlayer',
        role: 'SUPPORT' as const,
        tier: 'GOLD' as const,
        division: 'III' as const,
        leaguePoints: 70,
        championName: 'Thresh',
        championMastery: 5,
        gamesOnChampion: 35,
        winrateOnChampion: 48,
        kdaOnChampion: 2.2,
        globalWinrate: 49,
        totalGames: 210,
        isMainRole: true,
        isAutofill: false,
        recentWins: 4,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 0,
      },
    ],
  } as TeamData,
  opponentTeam: {
    players: [
      // Équipe similaire
      {
        summonerName: 'Enemy1',
        role: 'TOP' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 55,
        championName: 'Garen',
        championMastery: 5,
        gamesOnChampion: 28,
        winrateOnChampion: 51,
        kdaOnChampion: 2.4,
        globalWinrate: 50,
        totalGames: 195,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'Enemy2',
        role: 'JUNGLE' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 40,
        championName: 'Graves',
        championMastery: 6,
        gamesOnChampion: 45,
        winrateOnChampion: 50,
        kdaOnChampion: 2.6,
        globalWinrate: 50,
        totalGames: 205,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'Enemy3',
        role: 'MID' as const,
        tier: 'GOLD' as const,
        division: 'III' as const,
        leaguePoints: 65,
        championName: 'Zed',
        championMastery: 5,
        gamesOnChampion: 32,
        winrateOnChampion: 49,
        kdaOnChampion: 2.7,
        globalWinrate: 49,
        totalGames: 215,
        isMainRole: true,
        isAutofill: false,
        recentWins: 4,
        recentGames: 10,
        currentStreak: -1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'Enemy4',
        role: 'ADC' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 50,
        championName: 'Caitlyn',
        championMastery: 4,
        gamesOnChampion: 22,
        winrateOnChampion: 52,
        kdaOnChampion: 2.5,
        globalWinrate: 51,
        totalGames: 200,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'Enemy5',
        role: 'SUPPORT' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 35,
        championName: 'Nautilus',
        championMastery: 5,
        gamesOnChampion: 30,
        winrateOnChampion: 50,
        kdaOnChampion: 2.3,
        globalWinrate: 50,
        totalGames: 185,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
    ],
  } as TeamData,
};

// ==========================================
// CAS 2: Avantage Clair (OTP Challenger)
// ==========================================

export const CHALLENGER_OTP = {
  yourTeam: {
    players: [
      {
        summonerName: 'ChallengerOTP',
        role: 'MID' as const,
        tier: 'CHALLENGER' as const,
        division: null,
        leaguePoints: 800,
        championName: 'Yasuo',
        championMastery: 7,
        gamesOnChampion: 500, // OTP
        winrateOnChampion: 62,
        kdaOnChampion: 4.2,
        globalWinrate: 58,
        totalGames: 800,
        isMainRole: true,
        isAutofill: false,
        recentWins: 8,
        recentGames: 10,
        currentStreak: 5, // Win streak
        daysSinceLastGame: 0,
      },
      // ... reste de l'équipe Diamond+
      {
        summonerName: 'TopDiamond',
        role: 'TOP' as const,
        tier: 'DIAMOND' as const,
        division: 'II' as const,
        leaguePoints: 60,
        championName: 'Camille',
        championMastery: 6,
        gamesOnChampion: 80,
        winrateOnChampion: 56,
        kdaOnChampion: 2.9,
        globalWinrate: 54,
        totalGames: 400,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'JungleDiamond',
        role: 'JUNGLE' as const,
        tier: 'DIAMOND' as const,
        division: 'I' as const,
        leaguePoints: 40,
        championName: 'Elise',
        championMastery: 6,
        gamesOnChampion: 60,
        winrateOnChampion: 58,
        kdaOnChampion: 3.1,
        globalWinrate: 55,
        totalGames: 350,
        isMainRole: true,
        isAutofill: false,
        recentWins: 7,
        recentGames: 10,
        currentStreak: 3,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'ADCDiamond',
        role: 'ADC' as const,
        tier: 'DIAMOND' as const,
        division: 'III' as const,
        leaguePoints: 50,
        championName: 'Jhin',
        championMastery: 7,
        gamesOnChampion: 120,
        winrateOnChampion: 57,
        kdaOnChampion: 3.4,
        globalWinrate: 53,
        totalGames: 420,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'SupportDiamond',
        role: 'SUPPORT' as const,
        tier: 'DIAMOND' as const,
        division: 'II' as const,
        leaguePoints: 70,
        championName: 'Thresh',
        championMastery: 7,
        gamesOnChampion: 200,
        winrateOnChampion: 59,
        kdaOnChampion: 2.7,
        globalWinrate: 56,
        totalGames: 500,
        isMainRole: true,
        isAutofill: false,
        recentWins: 7,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
    ],
  } as TeamData,
  opponentTeam: {
    players: [
      // Équipe Platinum
      {
        summonerName: 'PlatTop',
        role: 'TOP' as const,
        tier: 'PLATINUM' as const,
        division: 'I' as const,
        leaguePoints: 70,
        championName: 'Malphite',
        championMastery: 5,
        gamesOnChampion: 40,
        winrateOnChampion: 52,
        kdaOnChampion: 2.4,
        globalWinrate: 51,
        totalGames: 250,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'PlatJungle',
        role: 'JUNGLE' as const,
        tier: 'PLATINUM' as const,
        division: 'II' as const,
        leaguePoints: 45,
        championName: 'Amumu',
        championMastery: 4,
        gamesOnChampion: 25,
        winrateOnChampion: 49,
        kdaOnChampion: 2.2,
        globalWinrate: 50,
        totalGames: 200,
        isMainRole: true,
        isAutofill: false,
        recentWins: 4,
        recentGames: 10,
        currentStreak: -2,
        daysSinceLastGame: 2,
      },
      {
        summonerName: 'PlatMid',
        role: 'MID' as const,
        tier: 'PLATINUM' as const,
        division: 'I' as const,
        leaguePoints: 55,
        championName: 'Syndra',
        championMastery: 5,
        gamesOnChampion: 35,
        winrateOnChampion: 51,
        kdaOnChampion: 2.5,
        globalWinrate: 51,
        totalGames: 230,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'PlatADC',
        role: 'ADC' as const,
        tier: 'PLATINUM' as const,
        division: 'II' as const,
        leaguePoints: 30,
        championName: 'Ashe',
        championMastery: 4,
        gamesOnChampion: 20,
        winrateOnChampion: 48,
        kdaOnChampion: 2.3,
        globalWinrate: 49,
        totalGames: 180,
        isMainRole: true,
        isAutofill: false,
        recentWins: 3,
        recentGames: 10,
        currentStreak: -1,
        daysSinceLastGame: 3,
      },
      {
        summonerName: 'PlatSupport',
        role: 'SUPPORT' as const,
        tier: 'PLATINUM' as const,
        division: 'I' as const,
        leaguePoints: 60,
        championName: 'Leona',
        championMastery: 5,
        gamesOnChampion: 45,
        winrateOnChampion: 53,
        kdaOnChampion: 2.6,
        globalWinrate: 52,
        totalGames: 260,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
    ],
  } as TeamData,
};

// ==========================================
// CAS 3: Match avec Autofills
// ==========================================

export const AUTOFILL_MATCH = {
  yourTeam: {
    players: [
      {
        summonerName: 'GoldTop',
        role: 'TOP' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 50,
        championName: 'Darius',
        championMastery: 6,
        gamesOnChampion: 50,
        winrateOnChampion: 54,
        kdaOnChampion: 2.7,
        globalWinrate: 52,
        totalGames: 300,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'AutofillJungle', // AUTOFILL !
        role: 'JUNGLE' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 40,
        championName: 'Warwick', // Champion "facile"
        championMastery: 2, // Peu joué
        gamesOnChampion: 5,
        winrateOnChampion: 40,
        kdaOnChampion: 1.8,
        globalWinrate: 51,
        totalGames: 280,
        isMainRole: false,
        isAutofill: true, // ← Pénalité -15
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'GoldMid',
        role: 'MID' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 55,
        championName: 'Ahri',
        championMastery: 5,
        gamesOnChampion: 40,
        winrateOnChampion: 53,
        kdaOnChampion: 2.9,
        globalWinrate: 52,
        totalGames: 310,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'GoldADC',
        role: 'ADC' as const,
        tier: 'GOLD' as const,
        division: 'II' as const,
        leaguePoints: 70,
        championName: 'Jinx',
        championMastery: 6,
        gamesOnChampion: 60,
        winrateOnChampion: 55,
        kdaOnChampion: 3.1,
        globalWinrate: 53,
        totalGames: 290,
        isMainRole: true,
        isAutofill: false,
        recentWins: 7,
        recentGames: 10,
        currentStreak: 3,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'OffRoleSupport', // OFF-ROLE
        role: 'SUPPORT' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 45,
        championName: 'Lux', // Support "dps"
        championMastery: 4,
        gamesOnChampion: 15,
        winrateOnChampion: 47,
        kdaOnChampion: 2.1,
        globalWinrate: 51,
        totalGames: 295,
        isMainRole: false, // Main role = Mid
        isAutofill: false,
        recentWins: 4,
        recentGames: 10,
        currentStreak: -1,
        daysSinceLastGame: 2,
      },
    ],
  } as TeamData,
  opponentTeam: {
    players: [
      // Équipe sans autofill
      {
        summonerName: 'EnemyTop',
        role: 'TOP' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 48,
        championName: 'Garen',
        championMastery: 5,
        gamesOnChampion: 45,
        winrateOnChampion: 52,
        kdaOnChampion: 2.5,
        globalWinrate: 51,
        totalGames: 290,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'EnemyJungle',
        role: 'JUNGLE' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 52,
        championName: 'LeeSin',
        championMastery: 7, // Main jungle
        gamesOnChampion: 150,
        winrateOnChampion: 56,
        kdaOnChampion: 3.0,
        globalWinrate: 53,
        totalGames: 400,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 2,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'EnemyMid',
        role: 'MID' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 50,
        championName: 'Zed',
        championMastery: 6,
        gamesOnChampion: 55,
        winrateOnChampion: 53,
        kdaOnChampion: 2.8,
        globalWinrate: 52,
        totalGames: 305,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
      {
        summonerName: 'EnemyADC',
        role: 'ADC' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 55,
        championName: 'Caitlyn',
        championMastery: 5,
        gamesOnChampion: 50,
        winrateOnChampion: 51,
        kdaOnChampion: 2.7,
        globalWinrate: 51,
        totalGames: 285,
        isMainRole: true,
        isAutofill: false,
        recentWins: 5,
        recentGames: 10,
        currentStreak: 0,
        daysSinceLastGame: 1,
      },
      {
        summonerName: 'EnemySupport',
        role: 'SUPPORT' as const,
        tier: 'GOLD' as const,
        division: 'I' as const,
        leaguePoints: 47,
        championName: 'Thresh',
        championMastery: 6,
        gamesOnChampion: 70,
        winrateOnChampion: 54,
        kdaOnChampion: 2.4,
        globalWinrate: 52,
        totalGames: 320,
        isMainRole: true,
        isAutofill: false,
        recentWins: 6,
        recentGames: 10,
        currentStreak: 1,
        daysSinceLastGame: 0,
      },
    ],
  } as TeamData,
};

// ==========================================
// FONCTION DE TEST
// ==========================================

export function runTests() {
  console.log('========================================');
  console.log('TEST 1: Match équilibré');
  console.log('========================================');
  const result1 = calculateMatchWinProbability(
    BALANCED_MATCH.yourTeam,
    BALANCED_MATCH.opponentTeam
  );
  console.log('Résultat:', result1);
  console.log('Attente: ~45-55% (match équilibré)\n');

  console.log('========================================');
  console.log('TEST 2: Avantage Challenger OTP');
  console.log('========================================');
  const result2 = calculateMatchWinProbability(
    CHALLENGER_OTP.yourTeam,
    CHALLENGER_OTP.opponentTeam
  );
  console.log('Résultat:', result2);
  console.log('Attente: ~75-85% (gros avantage)\n');

  console.log('========================================');
  console.log('TEST 3: Match avec Autofills');
  console.log('========================================');
  const result3 = calculateMatchWinProbability(
    AUTOFILL_MATCH.yourTeam,
    AUTOFILL_MATCH.opponentTeam
  );
  console.log('Résultat:', result3);
  console.log('Attente: ~35-45% (désavantage à cause autofill)\n');
}

// Décommenter pour tester :
// runTests();
