'use client';

import Link from 'next/link';
import Image from 'next/image';

export default function TermsOfService() {
  const sectionStyle = { marginBottom: '32px' };
  const h2Style = { fontSize: '24px', fontWeight: 600, color: 'white', marginBottom: '16px' };
  const h3Style = { fontSize: '20px', fontWeight: 500, color: 'white', marginTop: '24px', marginBottom: '12px' };
  const boxStyle = { marginTop: '16px', padding: '16px', background: 'rgba(255,255,255,0.05)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)' };
  const linkStyle = { color: '#22d3ee', textDecoration: 'none' };
  const listStyle = { marginLeft: '20px', marginTop: '16px' };

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0a0a0f', color: 'white' }}>
      {/* Navigation */}
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 24px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '10px', textDecoration: 'none', color: 'white' }}>
          <Image src="/nexra-logo.png" alt="Nexra" width={40} height={40} />
          <span style={{ fontFamily: 'Rajdhani, sans-serif', fontSize: '20px', fontWeight: 700, letterSpacing: '0.1em' }}>NEXRA</span>
        </Link>
        <Link href="/dashboard" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', fontSize: '14px', color: 'rgba(255,255,255,0.7)', textDecoration: 'none' }}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>
            <polyline points="9 22 9 12 15 12 15 22"/>
          </svg>
          Dashboard
        </Link>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '64px 24px' }}>
        <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '14px', color: 'rgba(255,255,255,0.5)', textDecoration: 'none', marginBottom: '32px' }}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M19 12H5M12 19l-7-7 7-7"/>
          </svg>
          Back to Home
        </Link>

        <h1 style={{ fontSize: '36px', fontWeight: 700, marginBottom: '32px', background: 'linear-gradient(to right, #22d3ee, #3b82f6)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          Terms of Service
        </h1>

        <div style={{ color: 'rgba(255,255,255,0.8)', lineHeight: 1.8 }}>
          <section style={sectionStyle}>
            <h2 style={h2Style}>1. Preamble</h2>
            <p>These Terms of Service (hereinafter "ToS") govern access to and use of the <strong style={{ color: '#22d3ee' }}>Nexra</strong> service, published by Crocoding.</p>
            <p style={{ marginTop: '16px' }}>By creating an account or using Nexra, you unreservedly accept these ToS. If you do not accept these terms, please do not use our service.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>2. Definitions</h2>
            <ul style={listStyle}>
              <li><strong>"Service"</strong>: refers to the Nexra platform and all its features</li>
              <li><strong>"User"</strong>: any person using the Service</li>
              <li><strong>"Account"</strong>: personal space created by the User on the Service</li>
              <li><strong>"Content"</strong>: data, analyses, and information generated by the Service</li>
              <li><strong>"Credits"</strong>: units used to access analysis features</li>
            </ul>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>3. Service Description</h2>
            <p>Nexra is an analysis and coaching platform for League of Legends. The Service offers:</p>
            <ul style={listStyle}>
              <li>Analysis of your matches using Riot Games API data</li>
              <li>Personalized advice generated by artificial intelligence</li>
              <li>Tracking of your statistics and progress</li>
              <li>Identification of your mistakes and areas for improvement</li>
            </ul>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>4. Registration and Account</h2>
            <h3 style={h3Style}>4.1 Registration Requirements</h3>
            <p>To use Nexra, you must:</p>
            <ul style={listStyle}>
              <li>Be at least 16 years old</li>
              <li>Provide accurate and complete information</li>
              <li>Have a valid Riot Games account to link your profile</li>
            </ul>
            <h3 style={h3Style}>4.2 Account Security</h3>
            <p>You are responsible for the confidentiality of your login credentials. Any activity performed from your account is presumed to be your own.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>5. Use of the Service</h2>
            <h3 style={h3Style}>5.1 Permitted Uses</h3>
            <p>The Service is intended for personal, non-commercial use. You may:</p>
            <ul style={listStyle}>
              <li>Analyze your own matches</li>
              <li>View your statistics and advice</li>
              <li>Use purchased credits for their intended purpose</li>
            </ul>
            <h3 style={h3Style}>5.2 Prohibited Uses</h3>
            <p>It is strictly prohibited to:</p>
            <ul style={listStyle}>
              <li>Use the Service for illegal or fraudulent purposes</li>
              <li>Attempt to bypass security measures</li>
              <li>Access other users' data without authorization</li>
              <li>Resell or transfer your account or credits</li>
              <li>Use bots or automated scripts</li>
            </ul>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>6. Credits and Payment</h2>
            <h3 style={h3Style}>6.1 Credit System</h3>
            <p>Match analyses consume credits. New users receive free credits upon registration.</p>
            <h3 style={h3Style}>6.2 Payments</h3>
            <p>Payments are processed securely via Stripe.</p>
            <h3 style={h3Style}>6.3 Refund Policy</h3>
            <p>Purchased credits are non-refundable, except in case of proven technical malfunction. Contact us at <a href="mailto:contact@crocoding.com" style={linkStyle}>contact@crocoding.com</a>.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>7. Intellectual Property</h2>
            <p>All elements of the Service (logos, texts, algorithms, interfaces, etc.) are the exclusive property of Crocoding or its partners.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>8. Relationship with Riot Games</h2>
            <p>Nexra uses the official Riot Games API in accordance with their terms of use.</p>
            <div style={boxStyle}>
              <p>Nexra is not endorsed by Riot Games and does not reflect the views of Riot Games. Riot Games and League of Legends are registered trademarks of Riot Games, Inc.</p>
            </div>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>9. Limitation of Liability</h2>
            <p>The Service is provided "as is". Analyses and advice provided by our AI are suggestions and do not constitute guarantees of results.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>10. Suspension and Termination</h2>
            <p>You may delete your account at any time. We reserve the right to suspend or terminate your account in case of violation of these ToS.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>11. Changes to ToS</h2>
            <p>We may modify these ToS at any time. Changes take effect upon publication on the website.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>12. Applicable Law and Disputes</h2>
            <p>These ToS are governed by French law. In the absence of an amicable agreement, the courts of Rouen shall have jurisdiction.</p>
          </section>

          <section style={sectionStyle}>
            <h2 style={h2Style}>13. Contact</h2>
            <p>For any questions, contact us at: <a href="mailto:contact@crocoding.com" style={linkStyle}>contact@crocoding.com</a></p>
          </section>

          <section style={{ paddingTop: '32px', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
            <p style={{ fontSize: '14px', color: 'rgba(255,255,255,0.5)' }}>Last updated: January 2025</p>
          </section>
        </div>

        {/* Navigation to other legal pages */}
        <div style={{ marginTop: '48px', paddingTop: '32px', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
          <h3 style={{ fontSize: '18px', fontWeight: 600, color: 'white', marginBottom: '16px' }}>Other Legal Documents</h3>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px' }}>
            <Link href="/legal" style={{ padding: '8px 16px', background: 'rgba(255,255,255,0.05)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)', color: 'white', textDecoration: 'none' }}>Legal Notice</Link>
            <Link href="/privacy" style={{ padding: '8px 16px', background: 'rgba(255,255,255,0.05)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)', color: 'white', textDecoration: 'none' }}>Privacy Policy</Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid rgba(255,255,255,0.1)', padding: '32px', marginTop: '64px' }}>
        <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center', color: 'rgba(255,255,255,0.5)', fontSize: '14px' }}>
          <p>&copy; 2025 Nexra - Crocoding. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
